// @ts-check
const fs = require('fs');
const path = require('path');
const {themes} = require('prism-react-renderer');

// --- Build-time fallback (overridden by generated data/*.json once the
// sync-from-drt PR lands). This is NOT a hand-maintained canonical list —
// data/destinations.json / data/sources.json always win when present. ---
const FALLBACK_DESTINATIONS = [{"type":"amplitude","name":"Amplitude"},{"type":"azure_blob","name":"Azure Blob Storage"},{"type":"bigquery","name":"BigQuery"},{"type":"clickhouse","name":"ClickHouse"},{"type":"databricks","name":"Databricks"},{"type":"discord","name":"Discord"},{"type":"elasticsearch","name":"Elasticsearch"},{"type":"email_smtp","name":"Email"},{"type":"file","name":"File"},{"type":"gcs","name":"Google Cloud Storage"},{"type":"github_actions","name":"GitHub Actions"},{"type":"google_ads","name":"Google Ads"},{"type":"google_sheets","name":"Google Sheets"},{"type":"hubspot","name":"HubSpot"},{"type":"intercom","name":"Intercom"},{"type":"jira","name":"Jira"},{"type":"linear","name":"Linear"},{"type":"mixpanel","name":"Mixpanel"},{"type":"mysql","name":"MySQL"},{"type":"notion","name":"Notion"},{"type":"parquet","name":"Parquet"},{"type":"postgres","name":"PostgreSQL"},{"type":"rest_api","name":"REST API"},{"type":"s3","name":"Amazon S3"},{"type":"salesforce_bulk","name":"Salesforce Bulk"},{"type":"sendgrid","name":"SendGrid"},{"type":"slack","name":"Slack"},{"type":"snowflake","name":"Snowflake"},{"type":"staged_upload","name":"Staged Upload"},{"type":"teams","name":"Microsoft Teams"},{"type":"twilio","name":"Twilio"},{"type":"zendesk","name":"Zendesk"}];
const FALLBACK_SOURCES = [{"type":"bigquery","name":"BigQuery"},{"type":"clickhouse","name":"ClickHouse"},{"type":"databricks","name":"Databricks"},{"type":"duckdb","name":"DuckDB"},{"type":"mysql","name":"MySQL"},{"type":"postgres","name":"PostgreSQL"},{"type":"redshift","name":"Redshift"},{"type":"rest_api","name":"REST API"},{"type":"snowflake","name":"Snowflake"},{"type":"sqlite","name":"SQLite"},{"type":"sqlserver","name":"SQL Server"}];

/**
 * Reads the SSoT inputs generated by sync-from-drt.yml (data/*.json, version.txt)
 * and exposes them to the site as global data. Falls back to the bundled lists
 * when the generated files aren't present yet, so the build is always green.
 */
function drtSsotPlugin() {
  return {
    name: 'drt-ssot-data',
    async loadContent() {
      const readJson = (rel, fallback) => {
        try {
          const raw = JSON.parse(fs.readFileSync(path.join(__dirname, rel), 'utf8'));
          const list = Array.isArray(raw) ? raw : raw.connectors;
          if (!Array.isArray(list) || list.length === 0) return fallback;
          return list.map((c) => ({type: c.type, name: c.display_name || c.name || c.type}));
        } catch (e) {
          return fallback;
        }
      };
      const readText = (rel) => {
        try {
          return fs.readFileSync(path.join(__dirname, rel), 'utf8').trim();
        } catch (e) {
          return '';
        }
      };
      return {
        destinations: readJson('data/destinations.json', FALLBACK_DESTINATIONS),
        sources: readJson('data/sources.json', FALLBACK_SOURCES),
        version: readText('data/version.txt'),
      };
    },
    async contentLoaded({content, actions}) {
      actions.setGlobalData(content);
    },
  };
}

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'drt',
  tagline: 'Reverse ETL for the code-first data stack',
  favicon: 'img/favicon.png',

  url: 'https://drt-hub.github.io',
  baseUrl: '/drt-web/',
  organizationName: 'drt-hub',
  projectName: 'drt-web',
  trailingSlash: false,

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  onBrokenAnchors: 'ignore',

  i18n: {defaultLocale: 'en', locales: ['en']},

  plugins: [drtSsotPlugin],

  stylesheets: [
    'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;450;500;600&family=JetBrains+Mono:wght@400;500;600&display=swap',
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        // Docs from synced-docs/ arrive in a follow-up PR (modular: hero first).
        docs: false,
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      image: 'img/logo.png',
      colorMode: {
        defaultMode: 'light',
        respectPrefersColorScheme: true,
      },
      navbar: {
        title: 'drt',
        logo: {alt: 'drt', src: 'img/logo.png'},
        items: [
          {to: '/#why', label: 'Why drt', position: 'left'},
          {to: '/#connectors', label: 'Connectors', position: 'left'},
          {to: '/#quickstart', label: 'Quickstart', position: 'left'},
          {href: 'https://pypi.org/project/drt-core/', label: 'PyPI', position: 'right'},
          {href: 'https://github.com/drt-hub/drt', label: 'GitHub', position: 'right'},
        ],
      },
      footer: {
        style: 'light',
        links: [
          {
            title: 'Product',
            items: [
              {label: 'Why drt', to: '/#why'},
              {label: 'Connectors', to: '/#connectors'},
              {label: 'Quickstart', to: '/#quickstart'},
              {label: 'PyPI', href: 'https://pypi.org/project/drt-core/'},
            ],
          },
          {
            title: 'Open source',
            items: [
              {label: 'drt', href: 'https://github.com/drt-hub/drt'},
              {label: 'drt-action', href: 'https://github.com/drt-hub/drt-action'},
              {label: 'drt-sandbox', href: 'https://github.com/drt-hub/drt-sandbox'},
            ],
          },
          {
            title: 'Community',
            items: [
              {label: 'Discussions', href: 'https://github.com/drt-hub/drt/discussions'},
              {label: 'Issues', href: 'https://github.com/drt-hub/drt/issues'},
              {label: 'X / Twitter', href: 'https://x.com/drt_hub'},
            ],
          },
        ],
        copyright: `© ${new Date().getFullYear()} drt-hub · Apache-2.0 · pip install drt-core`,
      },
      prism: {
        theme: themes.github,
        darkTheme: themes.dracula,
        additionalLanguages: ['bash', 'yaml'],
      },
    }),
};

module.exports = config;
