// Sidebar for the generated CLI reference. Autogenerated from the directory so
// a new drt command needs no change here — ordering comes from the
// sidebar_position frontmatter that scripts/gen-cli-reference.py emits.
module.exports = {
  cli: [{type: 'autogenerated', dirName: '.'}],
};
